@startuml
'https://plantuml.com/class-diagram

Class BotHandler{
public CommandService m_Commands
public static string m_Prefix;
public static DiscordSocketClient m_Client;
}

Class Program{
main()
}

Class Level{
const string SUFFIX_NAME = "_Level"
const string EXTENSION = ".bplist"
const string PATH = @"./Levels/"
BeatSaverFormat m_BeatSaverFormat
LevelFormat m_Level
int m_LevelID
bool m_MapAdded
bool m_MapDeleted
string m_SyncURL

Level(int p_LevelID) // Constructor

+ReWritePlaylist()
+GetAllCategory()
+DeleteLevel()
+AddMap()
+RemoveMap()
+FetchBeatMap()
}


Class Player {
static string m_FolderPath
bool m_HavePlayerInfo
LevelControllerFormat m_LevelController
string m_Path
ApiPlayer m_PlayerFull
Ulong m_PlayerID
PlayerPassFormat m_PlayerPass
List<ApiScoreInfo> m_PlayerScore
PlayerStatsFormat m_PlayerStats

Player(int p_PlayerID) // Constructor

+GetPlayerLevel()
+GetInfos()

+LoadSavedScore()
+LoadStats()
+LoadPass()

+FetchScores()
+FetchPass()

+ClearScore()
+ResetTrophy()
+ResetLevels()

+ReturnPass()

+SetLevelCategoryPass()
+GetStats()
+ReWritePass()
+ReWriteScore()
}

package Modules{
    Class PermissionHandler{
    class RequirePermissionAttribute : PreconditionAttribute
    +GetUserPermLevel()
    }

    Class AdminModule {
    +CreateRoles()
    
    +AddChannel()
    +ConfirmationChannel()
    +LoggingChannel()
    
    +BotInfo()
    
    +Link()
    +Unlink()
    
    +RejectUser()
    
    +RemoveChannel()

    +Scan()
    +SetLevel()
    
    +ResetConfig()
    +Shutdown()
    }
    
    Class RankingTeamModule {
     +EditMap()
    
    +AddMap()
    +RemoveMap()
    
    EditMapInteraction:
    -case: SelectLevelMenu
    
    
    EditMapButtonHandler:
    -case: ChangeLevel
    -case: ChangeCategory
    -case: ChangeCategoryInfo
    -case: ToggleManualWeight
    -case: ToggleAdminPing
    -case: ChangeMinScoreRequirement
    -case: ChangeInfoOnGGP
    -case: ChangeName
    -case: RemoveMap
    -case: Back
    -case: Close
    
    }
    
    Class ScoringTeamModule {
    +BanFromLeaderboard()
    
    +ChangeScore()
    +DownloadScore()
    +RemoveScore()
    }
    
    Class UserModule {
    
    +GetStarted()
    
    +Link()
    +Unlink()
    
    +Scan()
    
    +GetCategoryPlaylistPack()
    +GetPlaylist()
    +GetUnPassedPlaylist()
    
    +Progress()
    +Profile()
    +GetGrindPool()
        
    +GetInfo()
    +GetStarted()
   
    +Help()
    +Leaderboard()
    
    +Ping()


    +Trophy()
    
    +AccPingToggle()
    +PassPingToggle()
    }
}

package Controllers{
    Class MapLeaderboardController {
    
    }
    
    Class RoleController {
    }
    
    Class UserController {
    }
    
    Class PlayerLeaderboard{
    }
    
    Class AccLeaderboardController{
    }
    
    Class PassLeaderboardController{
    }
    
    Class ConfigController
    
    
    Class JsonDataBaseController{
    +CreateDirectory()
    }
}

package Formats{
    package ApiFormat{
    Class ApiOutputs
    Class BeatSaverFormat
    Class PlayerApiOutputs
    }
    package ControllerFormat{
    Class ConfigFormat
    Class LeaderboardControllerFormat
    Class LevelControllerFormat
    Class MapLeaderboardControllerFormat   
    }
    package LevelFormat{
    Class LevelOutputs
    }
    package PlayerFormat{
    Class PlayerPassFormat
    Class PlayerStatsFormat
    }
    Class RoleFormat
    Class SnipeFormat
    Class UserFormat
}

package Api{
Class ApiAccessAttribute{}
    Class WebApp{
        Start()
        Stop()
        OnContext(HttpListenerContext)
        
        Partial Class WebApp(
        
           GetPlayerInfo()
           GetProgress()
           GetLeaderboards()
           ScanPlayer()
           GetPlaylist()
           GetPlayerPlaylist()
        
        )
    }
}

PlayerLeaderboard <-- AccLeaderboardController
PlayerLeaderboard <-- PassLeaderboardController

Program *-- BotHandler

AdminModule  ... "0..*" Player
RankingTeamModule  ... "0..*" Player
ScoringTeamModule  ... "0..*" Player
UserModule  ... "0..1" Player

RankingTeamModule . "0..*" Level
UserModule .. "0..*" Level
Player . "0..*" Level

WebApp . "0..1" Player
WebApp .. "0..1" PassLeaderboardController
WebApp .. "0..1" AccLeaderboardController
WebApp .. "0..1" Level

UserModule *- "0..*" MapLeaderboardController
ScoringTeamModule *-  "0..*" MapLeaderboardController
UserModule *- "0..1" PassLeaderboardController
UserModule *- "0..1" AccLeaderboardController


@enduml